name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install modules
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Copy SW
      run: cp src/sw.js dist/

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist

  deploy:
      runs-on: ubuntu-latest

      needs: build

      steps:
        - name: Download build
          uses: actions/download-artifact@v2
          with:
            name: dist
            path: dist

        - name: Transfer build files to server
          uses: appleboy/scp-action@master
          with:
            host: 95.163.213.142
            username: ubuntu
            key: ${{ secrets.PRIVATE_KEY }}
            source: "dist/*"
            target: "/home/ubuntu/01-frontend/dist"
