name: CI

on:
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install modules
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Copy SW
      run: cp src/sw.js dist/

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist
